using CountPad.Application.Common.Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace CountPad.Api.Filters
{
	public class ApiExceptionFilterAttribute : ExceptionFilterAttribute
	{
		private readonly IDictionary<Type, Action<ExceptionContext>> _exceptionHandlers;

		public ApiExceptionFilterAttribute()
		{
			_exceptionHandlers = new Dictionary<Type, Action<ExceptionContext>>
			{
				{ typeof(ValidationException), HandleValidationException },
				{ typeof(NotFoundException), HandleNotFoundException },
				{ typeof(UnauthorizedAccessException), HandleUnauthorizedAccessException },
				{ typeof(ForbiddenAccessException), HandleForbiddenAccessException },
				{ typeof(AlreadyExistsException), HandleAlreadyExistsException }
			};
		}

		public override void OnException(ExceptionContext context)
		{
			HandleException(context);

			base.OnException(context);
		}

		private void HandleException(ExceptionContext context)
		{
			Type type = context.Exception.GetType();
			if (_exceptionHandlers.ContainsKey(type))
			{
				_exceptionHandlers[type].Invoke(context);
				return;
			}

			if (!context.ModelState.IsValid)
			{
				HandleInvalidModelStateException(context);
				return;
			}
		}

		private void HandleInvalidModelStateException(ExceptionContext context)
		{
			var details = new ValidationProblemDetails(context.ModelState)
			{
				Detail = context.Exception.Message
			};

			context.Result = new BadRequestObjectResult(details);

			context.ExceptionHandled = true;
		}

		private void HandleValidationException(ExceptionContext context)
		{
			var exception = (ValidationException)context.Exception;

			var details = new ValidationProblemDetails(exception.Errors)
			{
				Title = "Validation error occurred",
				Detail = exception.Message
			};

			context.Result = new BadRequestObjectResult(details);

			context.ExceptionHandled = true;
		}

		private void HandleNotFoundException(ExceptionContext context)
		{
			var exception = (NotFoundException)context.Exception;

			var details = new ProblemDetails()
			{
				Title = "The specified resource was not found.",
				Detail = exception.Message
			};

			context.Result = new NotFoundObjectResult(details);

			context.ExceptionHandled = true;
		}

		private void HandleUnauthorizedAccessException(ExceptionContext context)
		{
			var details = new ProblemDetails
			{
				Status = StatusCodes.Status401Unauthorized,
				Title = "Unauthorized",
			};

			context.Result = new ObjectResult(details)
			{
				StatusCode = StatusCodes.Status401Unauthorized
			};

			context.ExceptionHandled = true;
		}

		private void HandleForbiddenAccessException(ExceptionContext context)
		{
			var details = new ProblemDetails
			{
				Status = StatusCodes.Status403Forbidden,
				Title = "Forbidden",
			};

			context.Result = new ObjectResult(details)
			{
				StatusCode = StatusCodes.Status403Forbidden
			};

			context.ExceptionHandled = true;
		}

		private void HandleAlreadyExistsException(ExceptionContext context)
		{
			var exception = (AlreadyExistsException)context.Exception;

			var details = new ProblemDetails()
			{
				Title = "The specified resource already exists.",
				Detail = exception.Message
			};

			context.Result = new BadRequestObjectResult(details);

			context.ExceptionHandled = true;
		}
	}
}
